### ISSUE TITLE
scenario: instance.json not conform to shacl shape

### ISSUE THREAD

**Issue by robertschubert** [GAIA-X4PLC-AAD/ontology-management-base#62]
We introduced a new `CI pipeline` which checks if the _instance.json conforms to the shacl shapes (see README.md).

The _instance.json file is not conform to the shacl.
To reproduce it locally please follow the `CI pipeline` section in the README.md.

Note that there is a new section "known issues" which describes a Bug of the wizard when not instanciating an optional field which has mandatory sub fields.

**Comment by heuerfin** [comment]
Added a branch and resolved conflicts. The current version has no errors when I run it locally.

However, I think the https://github.com/GAIA-X4PLC-AAD/ontology-management-base/blob/main/georeference/georeference_shacl.ttl#L92 shacle has an issue since the regex for state does not match the example.

Furthermore, the https://github.com/GAIA-X4PLC-AAD/ontology-management-base/blob/main/general/general_shacl.ttl#L62 contract_id shouldnt be mandatory on metadata... Since it is not yet present when no contract was established.
